package Enum;

public enum Process {
    LOGIN, LOGOUT, TRANSFER, PAID_INVOICE, ADD_INVOICE, CHANGE_BALANCE,
    CHECK_MY_ACCOUNT, CHECK_CUSTOMER_ACCOUNT, READ_LIST_ACCOUNT, 
    READ_LIST_INVOICE, READ_LIST_PAID_INVOICE, READ_LIST_UNPAID_INVOICE,
    READ_ACCOUNT_INVOICE, CHECK_USER_LOGIN, READ_LIST_COMPANY, INSERT_DUMMY_DATA
}
